development:
  clients:
    default:
      database: shoppie_service_rails_development
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
test:
  clients:
    default:
      database: shoppie_service_rails_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
production:
  clients:
    default:
      database: shoppie_service_rails_production
        hosts:
          - <%= ENV.fetch("MONGODB_URI") %>